listen_addr: 10.99.0.1:53
metrics_addr: 10.99.0.1:8080 # New: Prometheus-style metrics & health check
request_timeout: 4s
cache_size: 10000          # New: Max number of cached DNS responses

filter_malware: true
filter_porn: true
filter_ads: true

whitelist:
  - yts.lt
  - thepiratebay.org

resolver_unfiltered:
  name: cloudflare-dns.com
  addr: 1.1.1.1:443
  url: https://1.1.1.1/dns-query

resolver_anti_malware:
  name: cloudflare-dns.com
  addr: 1.1.1.2:443
  url: https://1.1.1.2/dns-query

resolver_anti_porn:
  name: cloudflare-dns.com
  addr: 1.1.1.3:443
  url: https://1.1.1.3/dns-query

resolver_anti_ads:
  name: dns.adguard-dns.com
  addr: 94.140.14.14:443  # CHANGED: Port 853 -> 443 for DoH
  url: https://dns.adguard-dns.com/dns-query